// Generated by CoffeeScript 1.7.1
(function() {
  var http, shelljs;

  http = require("http");

  shelljs = require("shelljs");

  http.createServer(function(request, response) {
    var currentDir, hexoCmd, hexoDir, hexoPostsDir, nvmCmd, pullCmd, result;
    response.writeHead(200, {
      "Content-Type": "text/plain"
    });
    currentDir = '' + shelljs.pwd();
    hexoPostsDir = "" + currentDir + "/../source/_posts";
    hexoDir = "" + currentDir + "/../";
    shelljs.cd(hexoPostsDir);
    pullCmd = shelljs.exec("ls & git pull origin master ");
    if (pullCmd.code === 0) {
      console.log("pull successed!");
      if (!(shelljs.which('node'))) {
        nvmCmd = shelljs.exec("nvm use 0.12");
      }
      shelljs.cd(hexoDir);
      hexoCmd = shelljs.exec("hexo generate");
      if (hexoCmd.code !== 0) {
        console.log("hexo generate failed!");
      } else {
        console.log("hexo generate successed!");
      }
    } else {
      console.log("pull posts failed");
    }
    shelljs.cd(currentDir);
    result = '' + pullCmd.code;
    response.write(result);
    response.end();
  }).listen(8888);

}).call(this);
